require('key.remap')
require('packages.finder')
require('packages.dir')
require('packages.colors')
require('packages.lsp')
require('packages.undo')
require('packages.git')
require('packages.conda')
require('packages.mason')
require('packages.signature')
require('packages.secondone')
require('packages.codex')
print("Lua init loaded")

vim.wo.relativenumber = true
